// This file is automatically generated from base.txt
// DO NOT EDIT MANUALLY - your changes will be overwritten
// Edit the corresponding .txt file in text_definitions/ instead

use datalang::datalang;

datalang! {
	dictionary Base
	
	term Name {
	}
	
	term LastName {
	}
	
	term BirthDate {
	}
	
	term User has {
	    +Name
	
	    +LastName
	
	    +BirthDate
	}
}
