// This file is automatically generated from base.txt
// DO NOT EDIT MANUALLY - your changes will be overwritten
//
// To regenerate this file:
// 1. Edit base.txt in the text_definitions/ directory
// 2. Run `cargo build` or `cargo check` to trigger regeneration

use datalang::datalang;

datalang! {
	dictionary Base
	
	term Name {
	}
	
	term LastName {
	}
	
	term BirthDate {
	}
	
	term User has {
	    +Name
	
	    +LastName
	
	    +BirthDate
	}
}
