// This file is automatically generated from social_media.txt
// DO NOT EDIT MANUALLY - your changes will be overwritten
//
// To regenerate this file:
// 1. Edit social_media.txt in the text_definitions/ directory
// 2. Run `cargo build` or `cargo check` to trigger regeneration

use datalang::datalang;

datalang! {
	import Base
	
	term Handle {
	}
	
	SocialMediaUser {
	    +Base::Name
	    +Base::BirthDate
	
	    +Handle
	}
}
