// This file is automatically generated from social_media.txt
// DO NOT EDIT MANUALLY - your changes will be overwritten
// Edit the corresponding .txt file in text_definitions/ instead

use datalang::datalang;

datalang! {
	import Base
	
	term Handle {
	}
	
	SocialMediaUser {
	    +Base::Name
	    +Base::BirthDate
	
	    +Handle
	}
}
